[project]
name = "big-data-framework"
version = "0.1.0"
description = "Big Data Framework dataset generator lab"
readme = "README.md"
authors = [
    { name = "o-sitbon-ece", email = "oceanne.sitbon@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.37.0",
]

[project.scripts]
dataset-users = "big_data_framework.dataset_users:main"
dataset-orders = "big_data_framework.dataset_orders:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
